spring:
  data:
    mongodb:
      uri: mongodb+srv://kavanp7:FiAsPfUrGqFcFk8p@cluster0.xdxul.mongodb.net/
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
#  servlet:
#    context-path: /journal